# Generated by Django 5.1.3 on 2025-06-14 18:50

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_cancha', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('SALA', 'Fútbol Sala'), ('F7', 'Fútbol 7'), ('F11', 'Fútbol 11')], max_length=4)),
                ('superficie', models.CharField(choices=[('FUTBOL SALA', 'Fútbol sala'), ('CESPED ARTIFICIAL', 'Césped artificial'), ('CESPED NATURAL', 'Césped natural'), ('TIERRA', 'Tierra'), ('CEMENTO', 'Cemento')], max_length=50)),
                ('propiedad', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada')], max_length=7)),
                ('costo_partido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(blank=True, default=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/canchas_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(help_text='Introduce un email válido', max_length=150, unique=True, verbose_name='email')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO_ESPECIFICADO', 'Prefiero no decirlo'), ('OTRO', 'Otro')], default='NO_ESPECIFICADO', max_length=20, null=True)),
                ('posicion', models.CharField(blank=True, choices=[('DELANTERO', 'Delantero'), ('CENTROCAMPISTA', 'Centrocampista'), ('DEFENSA', 'Defensa'), ('PORTERO', 'Portero')], max_length=50, null=True)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('calificacion', models.FloatField(default=1000.0)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('banner_perfil', models.ImageField(blank=True, null=True, upload_to='banner_perfil/')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('team_shield', models.ImageField(blank=True, null=True, upload_to='images/team_shields/')),
                ('team_banner', models.ImageField(blank=True, null=True, upload_to='images/team_banners/')),
                ('tipo_equipo', models.CharField(choices=[('PARTIDO', 'Equipo para un partido'), ('PERMANENTE', 'Equipo permanente')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('partidos_jugados_permanente', models.PositiveIntegerField(default=0)),
                ('victorias_permanente', models.PositiveIntegerField(default=0)),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_captain_equipo', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(related_name='get_jugadores_equipo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_limite_inscripcion', models.DateTimeField(blank=True, help_text='Hasta cuándo se pueden inscribir los jugadores. Si se deja en blanco, se calculará una hora antes del partido.', null=True, verbose_name='Fecha Límite de Inscripción')),
                ('tipo', models.CharField(choices=[('SALA', 'Fútbol Sala'), ('F7', 'Fútbol 7'), ('F11', 'Fútbol 11')], max_length=4)),
                ('nivel', models.CharField(blank=True, choices=[('', 'Cualquier nivel'), ('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('PRO', 'Profesional/Muy Alto')], max_length=50, null=True)),
                ('modalidad', models.CharField(blank=True, choices=[('AMISTOSO', 'Amistoso'), ('COMPETITIVO', 'Competitivo')], max_length=11, null=True)),
                ('max_jugadores', models.PositiveIntegerField(help_text='Número total de jugadores para el partido (ambos equipos).', validators=[django.core.validators.MinValueValidator(2)])),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('Bizum', 'Bizum'), ('GRATIS', 'Gratuito')], max_length=13, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=10)),
                ('calificacion_actualizada', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cancha_partido', to='app.cancha')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_creador', to=settings.AUTH_USER_MODEL)),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_equipo_local', to='app.equipo')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_equipo_visitante', to='app.equipo')),
                ('jugadores', models.ManyToManyField(blank=True, related_name='get_jugadores_partido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('JUGADOR_PARTIDO', 'Jugador a Partido Abierto'), ('EQUIPO_PARTIDO', 'Equipo a Partido de Club')], max_length=15)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('pago_confirmado', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_equipo_inscripcion', to='app.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_jugador_inscripcion', to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_partido_inscripcion', to='app.partido')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_antes', models.FloatField()),
                ('calificacion_despues', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_historialElo', to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partido')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='partido_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_partido_equipos', to='app.partido'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_partido_resultado', to='app.partido')),
            ],
        ),
        migrations.CreateModel(
            name='InvitacionEquipo',
            fields=[
                ('id_invitacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='app.equipo')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('equipo', 'invitado'), name='unique_pending_invitation_per_user_team')],
            },
        ),
    ]
